Import("*")

DebugFlag("Hello")
DebugFlag("SimpleMemObject")

SimObject("HelloObject.py", sim_objects=["HelloObject", "GoodbyeObject"])
SimObject("SimpleMemObject.py", sim_objects=["SimpleMemObject"])

Source("hello_object.cc")
Source("goodbye_object.cc")
Source("simple_mem_object.cc")